### ISSUE TITLE
Shell script invocation error

### ISSUE THREAD

**Issue by mediakliq** [peter-iakovlev/MtProtoKit#2]
Does this work? is there a fix for this script error that occurs in the Telegram open source and in this version as well. Trying to figure out why Telegram would release and opensource code that does not build and has many errors. Thanks

**Comment by peter-iakovlev** [comment]
MtProtoKit requires https://github.com/kstenerud/iOS-Universal-Framework, so clone it and follow the instructions under "Real Framework".
