### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by PauloMigAlmeida** [peter-iakovlev/MtProtoKit#4]
@peter-iakovlev I was just wondering what is the license for this project ?

**Comment by Luccifer** [comment]
You are not 'Just wondering' https://libraries.io/cocoapods/MTProtoKit

**Comment by PauloMigAlmeida** [comment]
I actually still wondering since I need that info to update the cocoa pods with the correct license. If you know it, please just let me know ;)
